CREATE DATABASE IF NOT EXISTS personal_missions_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE personal_missions_db;

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    level INT DEFAULT 1,
    experience INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_login_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mission_types (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    goal_template VARCHAR(255) NOT NULL,
    reward_data JSON NOT NULL,
    requirements JSON,
    min_level_required INT DEFAULT 1,
    category VARCHAR(255) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS missions (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    mission_type_id VARCHAR(255) NOT NULL,
    status ENUM('assigned', 'in_progress', 'completed', 'failed', 'expired') DEFAULT 'assigned',
    progress INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    rewards_claimed BOOLEAN DEFAULT FALSE,
    objective_value INT NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (mission_type_id) REFERENCES mission_types(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO mission_types (id, name, description, goal_template, reward_data, min_level_required, category) VALUES
-- Накопительные (Accumulative)
('type_collect_wood', 'Сбор древесины', 'Собирай древесину.', 'Collect N wood', '{"type": "experience", "amount": 50}', 1, 'Accumulative'),
('type_defeat_goblins', 'Истребление гоблинов', 'Побеждай гоблинов.', 'Defeat N goblins', '{"type": "gold", "amount": 20}', 3, 'Killing'),
('type_hunt_wolves', 'Охота на волков', 'Охоться на волков.', 'Hunt N wolves', '{"type": "gold", "amount": 15}', 2, 'Killing'),
('type_mine_stone', 'Добыча камня', 'Добывай камень.', 'Mine N stone', '{"type": "experience", "amount": 30}', 1, 'Accumulative'),
('type_fish', 'Рыбная ловля', 'Лови рыбу.', 'Catch N fish', '{"type": "experience", "amount": 25}', 1, 'Accumulative'),
('type_collect_herbs', 'Сбор трав', 'Собирай травы.', 'Collect N herbs', '{"type": "experience", "amount": 20}', 1, 'Accumulative'),
('type_kill_bears', 'Охота на медведей', 'Охоться на медведей.', 'Kill N bears', '{"type": "gold", "amount": 40}', 4, 'Killing'),
('type_mine_coal', 'Добыча угля', 'Добывай уголь.', 'Mine N coal', '{"type": "experience", "amount": 35}', 2, 'Accumulative'),
('type_gather_apples', 'Сбор яблок', 'Собирай яблоки.', 'Gather N apples', '{"type": "experience", "amount": 15}', 1, 'Accumulative'),
('type_slay_orcs', 'Истребление орков', 'Побеждай орков.', 'Slay N orcs', '{"type": "gold", "amount": 35}', 5, 'Killing'),
('type_hunt_boars', 'Охота на кабанов', 'Охоться на кабанов.', 'Hunt N boars', '{"type": "gold", "amount": 25}', 3, 'Killing'),
('type_mine_iron', 'Добыча железа', 'Добывай железо.', 'Mine N iron', '{"type": "experience", "amount": 40}', 3, 'Accumulative'),
('type_farm_wheat', 'Выращивание пшеницы', 'Выращивай пшеницу.', 'Farm N wheat', '{"type": "experience", "amount": 30}', 2, 'Accumulative'),
('type_collect_flowers', 'Сбор цветов', 'Собирай цветы.', 'Collect N flowers', '{"type": "experience", "amount": 10}', 1, 'Accumulative'),
('type_kill_dragons', 'Охота на драконов', 'Охоться на драконов.', 'Kill N dragons', '{"type": "gold", "amount": 100}', 10, 'Killing'),
('type_mine_gold', 'Добыча золота', 'Добывай золото.', 'Mine N gold', '{"type": "gold", "amount": 50}', 6, 'Accumulative'),
('type_gather_mushrooms', 'Сбор грибов', 'Собирай грибы.', 'Gather N mushrooms', '{"type": "experience", "amount": 20}', 1, 'Accumulative'),
('type_slay_undead', 'Истребление нежити', 'Побеждай нежить.', 'Slay N undead', '{"type": "experience", "amount": 60}', 7, 'Killing'),
('type_hunt_deer', 'Охота на оленей', 'Охоться на оленей.', 'Hunt N deer', '{"type": "gold", "amount": 30}', 4, 'Killing'),
('type_mine_diamonds', 'Добыча алмазов', 'Добывай алмазы.', 'Mine N diamonds', '{"type": "gold", "amount": 100}', 8, 'Accumulative'),

-- Разовые (One-Time)
('type_find_treasure', 'Поиск сокровищ', 'Найди спрятанный клад.', 'Find the hidden treasure', '{"type": "item", "amount": 1, "item_type": "magic_scroll"}', 5, 'One-Time'),
('type_deliver_message', 'Доставка сообщения', 'Доставь важное письмо.', 'Deliver an important message', '{"type": "experience", "amount": 30}', 2, 'One-Time'),
('type_craft_potion', 'Изготовление зелья', 'Свари зелье исцеления.', 'Craft a healing potion', '{"type": "gold", "amount": 15}', 4, 'One-Time'),
('type_rescue_npc', 'Спасение NPC', 'Спаси узника.', 'Rescue a prisoner', '{"type": "experience", "amount": 40}', 5, 'One-Time'),
('type_solve_puzzle', 'Решение головоломки', 'Реши древнюю головоломку.', 'Solve an ancient puzzle', '{"type": "experience", "amount": 50}', 6, 'One-Time'),
('type_talk_to_npc', 'Разговор с NPC', 'Поговори с важным человеком.', 'Talk to an important NPC', '{"type": "experience", "amount": 10}', 1, 'One-Time'),
('type_visit_location', 'Посещение локации', 'Посети древний храм.', 'Visit an ancient temple', '{"type": "experience", "amount": 20}', 3, 'One-Time'),
('type_learn_spell', 'Изучение заклинания', 'Изучи новое заклинание.', 'Learn a new spell', '{"type": "experience", "amount": 70}', 8, 'One-Time'),
('type_train_skill', 'Тренировка навыка', 'Повысь навык владения мечом.', 'Train swordsmanship skill', '{"type": "experience", "amount": 25}', 2, 'One-Time'),
('type_donate_item', 'Пожертвование предмета', 'Пожертвуй редкий артефакт.', 'Donate a rare artifact', '{"type": "reputation", "amount": 10}', 4, 'One-Time'),
('type_read_book', 'Чтение книги', 'Прочитай древнюю книгу.', 'Read an ancient book', '{"type": "knowledge", "amount": 1}', 3, 'One-Time'),
('type_plant_tree', 'Посадка дерева', 'Посади дерево в пустыне.', 'Plant a tree in the desert', '{"type": "reputation", "amount": 5}', 2, 'One-Time'),
('type_clean_up', 'Уборка территории', 'Очисти лагерь от мусора.', 'Clean up the camp', '{"type": "experience", "amount": 15}', 1, 'One-Time'),
('type_protect_npc', 'Защита NPC', 'Защити торговца от бандитов.', 'Protect a merchant from bandits', '{"type": "gold", "amount": 25}', 4, 'One-Time'),
('type_negotiate_deal', 'Заключение сделки', 'Заключи мир между кланами.', 'Negotiate peace between clans', '{"type": "reputation", "amount": 15}', 6, 'One-Time'),
('type_investigate_crime', 'Расследование преступления', 'Расследуй кражу.', 'Investigate a theft', '{"type": "experience", "amount": 45}', 5, 'One-Time'),
('type_perform_show', 'Выступление', 'Выступи с представлением.', 'Perform a show', '{"type": "gold", "amount": 20}', 3, 'One-Time'),
('type_compete_in_race', 'Участие в гонках', 'Участвуй в гонках на лодках.', 'Compete in a boat race', '{"type": "gold", "amount": 30}', 4, 'One-Time'),
('type_win_tournament', 'Победа в турнире', 'Выиграй турнир по стрельбе из лука.', 'Win an archery tournament', '{"type": "gold", "amount": 50}', 7, 'One-Time'),
('type_make_peace', 'Заключение мира', 'Прими участие в мирных переговорах.', 'Participate in peace negotiations', '{"type": "reputation", "amount": 20}', 8, 'One-Time'),

-- Дополнительные накопительные
('type_collect_berries', 'Сбор ягод', 'Собирай ягоды.', 'Collect N berries', '{"type": "experience", "amount": 12}', 1, 'Accumulative'),
('type_kill_spiders', 'Уничтожение пауков', 'Убивай пауков.', 'Kill N spiders', '{"type": "gold", "amount": 8}', 2, 'Killing'),
('type_mine_copper', 'Добыча меди', 'Добывай медь.', 'Mine N copper', '{"type": "experience", "amount": 28}', 1, 'Accumulative'),
('type_farm_carrots', 'Выращивание моркови', 'Выращивай морковь.', 'Farm N carrots', '{"type": "experience", "amount": 18}', 1, 'Accumulative'),
('type_gather_logs', 'Сбор брёвен', 'Собирай брёвна.', 'Gather N logs', '{"type": "experience", "amount": 32}', 2, 'Accumulative'),
('type_kill_slimes', 'Уничтожение слизней', 'Убивай слизней.', 'Kill N slimes', '{"type": "experience", "amount": 10}', 1, 'Killing'),
('type_mine_tin', 'Добыча олова', 'Добывай олово.', 'Mine N tin', '{"type": "experience", "amount": 33}', 2, 'Accumulative'),
('type_farm_potatoes', 'Выращивание картофеля', 'Выращивай картофель.', 'Farm N potatoes', '{"type": "experience", "amount": 19}', 1, 'Accumulative'),
('type_collect_feathers', 'Сбор перьев', 'Собирай перья.', 'Collect N feathers', '{"type": "experience", "amount": 8}', 1, 'Accumulative'),
('type_kill_bats', 'Охота на летучих мышей', 'Охоться на летучих мышей.', 'Hunt N bats', '{"type": "gold", "amount": 5}', 1, 'Killing'),
('type_mine_silver', 'Добыча серебра', 'Добывай серебро.', 'Mine N silver', '{"type": "gold", "amount": 45}', 5, 'Accumulative'),
('type_farm_cabbage', 'Выращивание капусты', 'Выращивай капусту.', 'Farm N cabbage', '{"type": "experience", "amount": 16}', 1, 'Accumulative'),
('type_gather_branches', 'Сбор веток', 'Собирай ветки.', 'Gather N branches', '{"type": "experience", "amount": 14}', 1, 'Accumulative'),
('type_kill_skeletons', 'Истребление скелетов', 'Побеждай скелетов.', 'Slay N skeletons', '{"type": "gold", "amount": 12}', 3, 'Killing'),
('type_mine_lead', 'Добыча свинца', 'Добывай свинец.', 'Mine N lead', '{"type": "experience", "amount": 34}', 3, 'Accumulative'),
('type_farm_onions', 'Выращивание лука', 'Выращивай лук.', 'Farm N onions', '{"type": "experience", "amount": 17}', 1, 'Accumulative'),
('type_collect_leaves', 'Сбор листьев', 'Собирай листья.', 'Collect N leaves', '{"type": "experience", "amount": 9}', 1, 'Accumulative'),
('type_kill_zombies', 'Истребление зомби', 'Побеждай зомби.', 'Slay N zombies', '{"type": "gold", "amount": 10}', 2, 'Killing'),
('type_mine_nickel', 'Добыча никеля', 'Добывай никель.', 'Mine N nickel', '{"type": "experience", "amount": 36}', 4, 'Accumulative'),
('type_farm_turnips', 'Выращивание репы', 'Выращивай репу.', 'Farm N turnips', '{"type": "experience", "amount": 15}', 1, 'Accumulative'),

-- Дополнительные разовые
('type_find_secret_room', 'Поиск потайной комнаты', 'Найди потайную комнату в замке.', 'Find a secret room in the castle', '{"type": "item", "amount": 1, "item_type": "ancient_key"}', 6, 'One-Time'),
('type_deliver_gift', 'Доставка подарка', 'Доставь подарок к празднику.', 'Deliver a gift for the festival', '{"type": "reputation", "amount": 8}', 2, 'One-Time'),
('type_craft_tool', 'Изготовление инструмента', 'Создай новый инструмент.', 'Craft a new tool', '{"type": "experience", "amount": 35}', 4, 'One-Time'),
('type_rescue_animal', 'Спасение животного', 'Спаси заблудившееся животное.', 'Rescue a lost animal', '{"type": "reputation", "amount": 6}', 2, 'One-Time'),
('type_solve_mystery', 'Решение загадки', 'Реши загадку старого мудреца.', 'Solve the riddle of the old sage', '{"type": "knowledge", "amount": 2}', 7, 'One-Time'),
('type_teach_child', 'Обучение ребёнка', 'Научи ребёнка читать.', 'Teach a child to read', '{"type": "reputation", "amount": 10}', 3, 'One-Time'),
('type_explore_ruins', 'Исследование руин', 'Исследуй древние руины.', 'Explore ancient ruins', '{"type": "experience", "amount": 60}', 6, 'One-Time'),
('type_learn_recipe', 'Изучение рецепта', 'Выучи рецепт вкусной еды.', 'Learn a recipe for delicious food', '{"type": "knowledge", "amount": 1}', 3, 'One-Time'),
('type_practice_magic', 'Практика магии', 'Потренируй заклинание телепортации.', 'Practice the teleportation spell', '{"type": "experience", "amount": 55}', 7, 'One-Time'),
('type_donate_money', 'Пожертвование денег', 'Пожертвуй деньги на благотворительность.', 'Donate money to charity', '{"type": "reputation", "amount": 12}', 4, 'One-Time'),
('type_write_poem', 'Написание стихотворения', 'Напиши стихотворение для возлюбленной.', 'Write a poem for your beloved', '{"type": "reputation", "amount": 5}', 2, 'One-Time'),
('type_build_shelter', 'Постройка укрытия', 'Построй укрытие для беженцев.', 'Build shelter for refugees', '{"type": "reputation", "amount": 15}', 5, 'One-Time'),
('type_clean_river', 'Очистка реки', 'Очисти реку от мусора.', 'Clean the river from pollution', '{"type": "reputation", "amount": 10}', 3, 'One-Time'),
('type_protect_village', 'Защита деревни', 'Защити деревню от набега.', 'Protect the village from a raid', '{"type": "gold", "amount": 40}', 5, 'One-Time'),
('type_negotiate_trade', 'Переговоры о торговле', 'Организуй торговую сделку.', 'Organize a trade agreement', '{"type": "reputation", "amount": 18}', 7, 'One-Time'),
('type_investigate_murder', 'Расследование убийства', 'Расследуй загадочное убийство.', 'Investigate a mysterious murder', '{"type": "experience", "amount": 75}', 8, 'One-Time'),
('type_perform_concert', 'Выступление на концерте', 'Выступи с концертом.', 'Perform at a concert', '{"type": "gold", "amount": 60}', 6, 'One-Time'),
('type_compete_in_contest', 'Участие в конкурсе', 'Участвуй в конкурсе поваров.', 'Compete in a cooking contest', '{"type": "gold", "amount": 35}', 4, 'One-Time'),
('type_win_competition', 'Победа в соревновании', 'Выиграй соревнование по бегу.', 'Win a running competition', '{"type": "gold", "amount": 45}', 5, 'One-Time'),
('type_make_alliance', 'Заключение альянса', 'Помоги заключить альянс.', 'Help form an alliance', '{"type": "reputation", "amount": 25}', 9, 'One-Time'),

-- Ивентовые
('type_find_peace', 'Поиск мира', 'Попытайся найти мир во время войны. Удачи.', 'Find peace during war', '{"type": "experience", "amount": 999}', 10, 'One-Time'),
('type_count_corpses', 'Подсчёт трупов', 'Сосчитай, сколько трупов ты оставил после себя.', 'Count corpses left behind', '{"type": "reputation", "amount": -100}', 1, 'Accumulative'),
('type_feed_giants', 'Кормление великанов', 'Принеси великанам еду. Или просто принеси себя.', 'Feed the giants', '{"type": "experience", "amount": 10}', 1, 'One-Time'),
('type_clean_graveyard', 'Уборка кладбища', 'Наведи порядок на кладбище. Своими руками.', 'Clean up the graveyard', '{"type": "experience", "amount": 5}', 1, 'One-Time'),
('type_rescue_drowning_man', 'Спасти тонущего', 'Спаси утопающего. Он потом поблагодарит... из могилки.', 'Rescue a drowning man', '{"type": "reputation", "amount": 10}', 3, 'One-Time'),
('type_buy_horse', 'Купить лошадь', 'Купи лошадь. Убедись, что она не призрак.', 'Buy a horse', '{"type": "gold", "amount": 50}', 2, 'One-Time'),
('type_find_true_love', 'Найти истинную любовь', 'Найди свою вторую половинку. В могиле.', 'Find true love', '{"type": "experience", "amount": 500}', 10, 'One-Time'),
('type_steal_from_poor', 'Украсть у бедного', 'Укради хлеб у нищего. Он всё равно умрёт.', 'Steal from the poor', '{"type": "gold", "amount": 1}', 1, 'One-Time'),
('type_help_beggar', 'Помочь нищему', 'Дай монетку нищему. Он умрёт, но счастливым.', 'Help a beggar', '{"type": "reputation", "amount": 1}', 1, 'One-Time'),
('type_build_wall', 'Построить стену', 'Построй стену. Из костей.', 'Build a wall', '{"type": "experience", "amount": 40}', 5, 'One-Time'),
('type_dance_with_deaths', 'Танец со смертью', 'Потанцуй с костлявой. Она пригласит.', 'Dance with Death', '{"type": "experience", "amount": 100}', 8, 'One-Time'),
('type_heal_the_dead', 'Лечение мертвецов', 'Попробуй вылечить зомби. У тебя не получится.', 'Heal the dead', '{"type": "experience", "amount": 1}', 1, 'One-Time'),
('type_count_stars', 'Считать звёзды', 'Сосчитай, сколько звёзд на небе. Это займёт вечность.', 'Count the stars', '{"type": "experience", "amount": 1}', 1, 'Accumulative'),
('type_drink_poison', 'Выпить яд', 'Выпей яд. Это бесплатно.', 'Drink poison', '{"type": "experience", "amount": 1000}', 1, 'One-Time'),
('type_survive_nightmare', 'Выжить в кошмаре', 'Продержись ночь в собственных кошмарах.', 'Survive a nightmare', '{"type": "experience", "amount": 50}', 4, 'One-Time'),
('type_talk_to_gravestone', 'Разговор с надгробием', 'Поговори с надгробием. Оно не ответит, но ты почувствуешь себя лучше.', 'Talk to a gravestone', '{"type": "experience", "amount": 5}', 1, 'One-Time'),
('type_find_happiness', 'Найти счастье', 'Найди счастье в этом мире. Оно не существует.', 'Find happiness', '{"type": "experience", "amount": 0}', 1, 'One-Time'),
('type_eat_soup', 'Съесть суп', 'Съешь тарелку супа. Он из твоих надежд.', 'Eat soup', '{"type": "experience", "amount": 1}', 1, 'One-Time'),
('type_watch_sunrise', 'Наблюдать восход', 'Понаблюдай за восходом. Он последний.', 'Watch the sunrise', '{"type": "experience", "amount": 10}', 1, 'One-Time'),
('type_hug_a_bear', 'Обнять медведя', 'Обними медведя. Он ответит взаимностью.', 'Hug a bear', '{"type": "experience", "amount": 50}', 3, 'One-Time'),
('type_kiss_a_skull', 'Поцелуй череп', 'Поцелуй череп. Получи благословение.', 'Kiss a skull', '{"type": "reputation", "amount": -5}', 1, 'One-Time'),
('type_dig_own_grave', 'Выкопать собственную могилу', 'Выкопай яму. Возможно, свою.', 'Dig your own grave', '{"type": "experience", "amount": 20}', 2, 'One-Time'),
('type_burn_books', 'Сжечь книги', 'Сожги книги. Знания — это боль.', 'Burn books', '{"type": "reputation", "amount": -20}', 6, 'One-Time'),
('type_plant_corpses', 'Посадить трупы', 'Посади трупы. Вырастет лес смерти.', 'Plant corpses', '{"type": "experience", "amount": 30}', 4, 'One-Time'),
('type_listen_to_silence', 'Слушать тишину', 'Послушай тишину. Она кричит.', 'Listen to silence', '{"type": "experience", "amount": 5}', 1, 'One-Time'),
('type_count_deaths', 'Считать смерти', 'Сосчитай, сколько людей ты убил. Ты потерял счёт.', 'Count deaths', '{"type": "experience", "amount": 10}', 1, 'Accumulative'),
('type_cure_loneliness', 'Вылечить одиночество', 'Найди способ вылечить одиночество. Его нет.', 'Cure loneliness', '{"type": "experience", "amount": 1}', 1, 'One-Time'),
('type_drown_in_tears', 'Утонуть в слезах', 'Утони в собственных слезах.', 'Drown in tears', '{"type": "experience", "amount": 25}', 3, 'One-Time'),
('type_eat_ashes', 'Съесть пепел', 'Съешь горсть пепла. Вкус надежды.', 'Eat ashes', '{"type": "experience", "amount": 1}', 1, 'One-Time'),
('type_kiss_death', 'Поцелуй смерти', 'Поцелуй смерть. Она не отвечает.', 'Kiss Death', '{"type": "experience", "amount": 100}', 10, 'One-Time'),
('type_hunt_yourself', 'Охота на себя', 'Охоться на самого себя. Кто победит?', 'Hunt yourself', '{"type": "experience", "amount": 500}', 10, 'One-Time'),
('type_dream_of_peace', 'Мечтать о мире', 'Помечтай о мире. Проснись.', 'Dream of peace', '{"type": "experience", "amount": 1}', 1, 'One-Time'),
('type_cry_for_no_reason', 'Плакать без причины', 'Поплачь без причины. Причина есть всегда.', 'Cry for no reason', '{"type": "experience", "amount": 5}', 1, 'One-Time'),
('type_burn_memories', 'Сжечь воспоминания', 'Сожги все воспоминания. Ты забудешь, кто ты.', 'Burn memories', '{"type": "experience", "amount": 100}', 7, 'One-Time'),
('type_laugh_at_funeral', 'Смеяться на похоронах', 'Похихикивай на похоронах. Люди оценят.', 'Laugh at a funeral', '{"type": "reputation", "amount": -10}', 2, 'One-Time'),
('type_feed_cats_corpses', 'Кормить котов трупами', 'Покорми бездомных котов человечиной.', 'Feed cats corpses', '{"type": "experience", "amount": 15}', 3, 'One-Time'),
('type_find_light', 'Найти свет', 'Найди свет в конце тоннеля. Это поезд.', 'Find light at the end of tunnel', '{"type": "experience", "amount": 1}', 1, 'One-Time'),
('type_bury_your_past', 'Похоронить прошлое', 'Похорони своё прошлое. Оно будет скучать.', 'Bury your past', '{"type": "experience", "amount": 50}', 5, 'One-Time'),
('type_sing_to_the_dead', 'Петь мертвецам', 'Спой песню мертвецам. Они аплодируют.', 'Sing to the dead', '{"type": "experience", "amount": 20}', 4, 'One-Time'),
('type_drink_blood', 'Пить кровь', 'Выпей стакан крови. Не спрашивай, чьей.', 'Drink blood', '{"type": "experience", "amount": 10}', 2, 'One-Time'),
('type_sleep_in_graveyard', 'Спать на кладбище', 'Проведи ночь на кладбище. Призраки не уйдут.', 'Sleep in a graveyard', '{"type": "experience", "amount": 30}', 4, 'One-Time'),
('type_hug_a_zombie', 'Обнять зомби', 'Обними зомби. Он ответит поцелуем.', 'Hug a zombie', '{"type": "experience", "amount": 25}', 3, 'One-Time'),
('type_count_graves', 'Считать могилы', 'Сосчитай, сколько могил. Одна твоя.', 'Count graves', '{"type": "experience", "amount": 5}', 1, 'Accumulative'),
('type_dance_on_graves', 'Танцевать на могилах', 'Потанцуй на могилах. Мертвецы завидуют.', 'Dance on graves', '{"type": "reputation", "amount": -5}', 2, 'One-Time'),
('type_cook_human_flesh', 'Готовить человечину', 'Приготовь ужин. Главное — не задумываться.', 'Cook human flesh', '{"type": "experience", "amount": 40}', 6, 'One-Time'),
('type_watch_world_burn', 'Наблюдать, как горит мир', 'Понаблюдай, как мир сгорает. Ты поджёг.', 'Watch the world burn', '{"type": "experience", "amount": 100}', 8, 'One-Time'),
('type_pray_to_void', 'Молиться пустоте', 'Помолись пустоте. Никто не услышит.', 'Pray to the void', '{"type": "experience", "amount": 1}', 1, 'One-Time'),
('type_eat_heart', 'Съесть сердце', 'Съешь чье-то сердце. Оно ещё бьётся.', 'Eat a heart', '{"type": "experience", "amount": 50}', 7, 'One-Time'),
('type_find_meaning', 'Найти смысл жизни', 'Найди смысл жизни. Его нет.', 'Find the meaning of life', '{"type": "experience", "amount": 0}', 10, 'One-Time'),
('type_kiss_grave', 'Поцеловать могилу', 'Поцелуй надгробие. Покойник доволен.', 'Kiss a grave', '{"type": "reputation", "amount": -1}', 1, 'One-Time'),

('type_burn_hopes', 'Сжечь надежды', 'Сожги все надежды. Тепло.', 'Burn hopes', '{"type": "experience", "amount": 10}', 2, 'One-Time');
